name: Mobdrop Suggestion
description: Suggest a mobdrop related idea for MineInAbyss
body:
  - type: input
    attributes:
      label: Related mob
      description: What mob does this drop apply to?
      placeholder: Splitjaw
    validations:
      required: true

  - type: input
    attributes:
      label: Mobdrop name
      description: What is the name of the drop?
      placeholder: Splitjaw Scales
    validations:
      required: true

  - type: input
    attributes:
      label: Mobdrop Item
      description: What is the item this drop replaces?
      placeholder: Popped Chorus Fruit
    validations:
      required: true

  - type: textarea
    attributes:
      label: Mobdrop Texture
      description: |
        Do you have a custom texture, or ideas for one?
        If so you can drop/link an image below, or add details in the form of text.
    validations:
      required: false

  - type: input
    attributes:
      label: Related recipe ideas
      description: |
        Are there any suggested recipes related to this drop?
        If so mention them with '#ISSUE_NUMBER' below
      placeholder: '#10 and #12'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional info
      description: If you feel like additional information would be helpful add it here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have searched for and ensured there isn't already an open suggestion similar to this.
          required: true
        - label: I have ensured the mobdrop I'm requesting isn't already in the server.
          required: true